sudo: required
language: node_js
node_js:
  - "7.8"
cache:
  yarn: true
  directories:
    - node_modules

branches:  # exclude tags
  except:
    - /^\d+$/

env:
  global:
    # compiler command for Travis
    - CXX=g++-4.8
    # build number used by blt pipeline
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - secure : "PwdqejbAT+2GcRDbZEgFayjV24iQvMqNDFhrVS4mc6LF4x3GxDflkvM0f/hzP+Gz5Nk3Aj9EwAh3ULjrw4jV7cIjepJRiBNZ2CVne8k3LyYBxYydCTekLaArjBczAUpTI8tzAFgpYJdLGi7aZ4e+5dNIC8CFNMIrvs4VFTWK6iIRi/QcD0axCrPVL8imCHD1lYv+1P9rkRTLXPGELVUdxR3tk6iEASgcWiD9GgzG38tw53fZNAX8udTtY8sPhqNsTd3TajMBfgClsW72qFpX1hi0bj97xyp/O0sNslfS3+OuAtc4TGXVHD9YXrPcANXrM0uCCl/o1b7JW1cdp2kyENnSXCK1DK5JHCByFiGQ7dpMRdDptL2FXkB2m1Hmm50APjuKq2TCqr/ew1r4yCiAwrcTZtyz21SXkRGbCqVvR3A3SagdA7pJYpNbkNG9IJznbxZI6dY3TWcKWfSnITguErnZ0Y7NDfqwBCI5KUKrsJtBLmFeJPx88UVEaz2Gi6F53I64twyMQZv7Nbmp7jSVYWVPe9Q/6bfPBe8OPdKL1vJ+YdnGtHvbhmol6UKZ1hTaDCNuF1JdP1PBdMhntRzly2W1X4PzvYPsGEfvYrkOBPTdCkxl/5HKJ1X9IQdQIODN5tTnUzngZFxMnaNrI0W03jRu3xbpTyxL2iWwWR71g24="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - openssl aes-256-cbc -K $encrypted_e09404c5d59a_key -iv $encrypted_e09404c5d59a_iv -in github_deploy_key.enc -out github_deploy_key -d
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - $(npm bin)/set-up-ssh --key "$encrypted_e09404c5d59a_key" \
     --iv "$encrypted_e09404c5d59a_iv" \
     --path-encrypted-key ".travis/github_deploy_key.enc"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export GIT_TAG=$(make version) ||
    export GIT_TAG=$(make version)-beta
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] && [ "${TRAVIS_PULL_REQUEST}" = "false" ] &&
    export NPM_TAG=latest ||
    export NPM_TAG=beta
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" = "master" ] &&
    git commit -am "Commit .npmrc in tag pushed to npm" &&
    npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    git push -q https://$GITHUB_USER:$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG --tags &&
    npm publish --tag $NPM_TAG ||
    echo "skipping versioning"

notifications:
  # slack integration
  slack:
    # encrypted token for the meetuphq slack channel
    secure: J7M6eSgKWcbMqFs9Z2wSiHemn/IGOj8D/iB6AB2WXPYxr8+HQnzE6L96lmdwwSHNscB0tbg7y7xsMJHh+qeiiFgrMTAP7SbbT0kV9JdFWEJs4mwZtMBeQXbyfIJ/6HSFAsAjOxBgyhNnmx6PYKWKc+HGVcRui4dWJQRO24Nmfup93gJon63U/KsdXyvTpVN/dZ2EneQzhh/Evg0fXRxo9ETeqfeJ7KNTc0FvklVYdMe0d9cPKZ7/22qoYM7KKELE5ER/pDEeU42ttz4axm1l7WQAddDTQElH1oZP46Eq62Adu244bSuQUBIRwSBJOjUMnIzxn+2s3u4BfeSSGm9d8X8PD46fcaIKbIQaYOnlL9IK4s8jUhv1j0/qEHm3X5OJ7nrHM1FEmlY8R/lgCPyFI6Rr1z722n2iCxKrsasqFaF4bNQjp1L1hHmuFS1bAsGYouc6IRYVLntl0KHI5RpLWxCf6s3kaYHRb8sKcrZTXK+lf/Hlk0iWfXK+SU5vdKtjSrIJusWBU5AmcDKJbjTBbi85/zxJ86jYJy0WN2HsyR6K2mm+iGwTcBD52Ut/7J3PcHgJyp9kq+NQIxyuyk1PmGFWwy6N+xpirlFo7ztgSSEa2teD0gb9Feh1XaLiuAXtmMyaO8esAbXqygweLJGSXoTQgvjJ1Bvgb5GJSej0LME=

    # dont notify successful builds
    on_success: never

    # always notify build failures
    on_failure: always

