language: node_js
node_js:
  - '12.14'

cache:
  yarn: true
  directories:
    - node_modules

branches:  # exclude tags
  except:
    - /^v\d+\.\d+.\d+(-\S*)?$/

env:
  global:
    - CI_BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
    - secure : "PwdqejbAT+2GcRDbZEgFayjV24iQvMqNDFhrVS4mc6LF4x3GxDflkvM0f/hzP+Gz5Nk3Aj9EwAh3ULjrw4jV7cIjepJRiBNZ2CVne8k3LyYBxYydCTekLaArjBczAUpTI8tzAFgpYJdLGi7aZ4e+5dNIC8CFNMIrvs4VFTWK6iIRi/QcD0axCrPVL8imCHD1lYv+1P9rkRTLXPGELVUdxR3tk6iEASgcWiD9GgzG38tw53fZNAX8udTtY8sPhqNsTd3TajMBfgClsW72qFpX1hi0bj97xyp/O0sNslfS3+OuAtc4TGXVHD9YXrPcANXrM0uCCl/o1b7JW1cdp2kyENnSXCK1DK5JHCByFiGQ7dpMRdDptL2FXkB2m1Hmm50APjuKq2TCqr/ew1r4yCiAwrcTZtyz21SXkRGbCqVvR3A3SagdA7pJYpNbkNG9IJznbxZI6dY3TWcKWfSnITguErnZ0Y7NDfqwBCI5KUKrsJtBLmFeJPx88UVEaz2Gi6F53I64twyMQZv7Nbmp7jSVYWVPe9Q/6bfPBe8OPdKL1vJ+YdnGtHvbhmol6UKZ1hTaDCNuF1JdP1PBdMhntRzly2W1X4PzvYPsGEfvYrkOBPTdCkxl/5HKJ1X9IQdQIODN5tTnUzngZFxMnaNrI0W03jRu3xbpTyxL2iWwWR71g24="

before_install:
  - openssl aes-256-cbc -K $encrypted_e09404c5d59a_key -iv $encrypted_e09404c5d59a_iv -in '.travis/github_deploy_key.enc' -out github_deploy_key -d
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

  # install more recent `yarn`
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.21.1
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version

after_script:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - $(yarn bin)/set-up-ssh --key "$encrypted_e09404c5d59a_key" --iv "$encrypted_e09404c5d59a_iv" --path-encrypted-key ".travis/github_deploy_key.enc"
  - >
    if [ ${TRAVIS_BRANCH} = "master" ] && [ ${TRAVIS_PULL_REQUEST} = "false" ]; then
      export GIT_TAG=$(make version)
      export NPM_TAG=latest
    else
      export GIT_TAG=$(make version)-beta
      export NPM_TAG=beta
    fi
  - echo "GIT_TAG=$GIT_TAG"
  - echo "NPM_TAG=$NPM_TAG"
  - >
    [ "${TRAVIS_BRANCH}" != "master" ] &&
    echo "skipping versioning" ||
    yarn run build &&
    git commit -am "Commit .npmrc in tag pushed to npm" &&
    npm version $GIT_TAG -m "Version $GIT_TAG built by Travis CI - https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_JOB_ID" &&
    git push --tags git@github.com:$TRAVIS_REPO_SLUG.git &&
    npm publish --tag $NPM_TAG

notifications:
  # slack integration
  slack:
    # encrypted token for the meetuphq slack channel
    secure: "oW5B1Yow4dWFo8taSIcnR6PJX+V8SC1Af0Irec6JpfEDzKD4oFxY4UliROXKNiZzNHY4qqwtFGr9JSnHzQtnllhjD3RPwzlDYvwMXRrv2BYiQIX4Cod8P/SjjWPCX2j9qMijAVtViY+m5/OYK60/N5K+h0OS9KIhSl1NDJpDOsGDB+WZOVycHX3F6a3rSThgNaN8Ln34CqoFDmbidsYpuW3TP4QXbDbvT8bBnWyxWBgyOKEclUtyGGYCBuNjNEz7mfgEGAVqrLeyQANBu5BEoyP9n473LDHeM18IDbUh4yju1vAM5J/PPMiotoFcNR1ldEYKgoOcODONIQ7X6z9/1u7tA2AnJKkMZkFOJ3dLg+fGx8yTPO+jKUY0x0g7h1lsw0Re4GCyPuAlRTCYuWK1hvqIUEIhbPQF+XAFrhHcv1Ua5N7HHw2Nlu62q/j85GQHyKiWvu/FFM2TSEne+vA1DjliYLwhaNhiG6zVGKfEC2cM7yHtGxBhKrnKDw/wpBGn0d9hVVmmULJU2IZA/OmtvU/4o9nbSBWVHzGkmxgOL//6pRy67yORpsvtkffZFic2IN4GIcSuvgOLPvGtfSq44FW5wmEn6DuHihTHKfuIzZ3KjLgzwwFtNtVm2laxTds/PyG1zurIPN2mRVnms5ms/vbV9wErSm/Z0gAj74uB4sc="
